version: 2

updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/packages/cross-csl-*"
      - "/test-app-mobile"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 3
    groups:
      npm-dependencies:
        patterns:
          - "*"
        group-by: "dependency-name"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "11:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 1
