name: Dependency Review

on:
  pull_request:
    paths:
      - "package.json"
      - "package-lock.json"
      - "yarn.lock"
      - "packages/cross-csl-*/package.json"
      - "packages/cross-csl-*/package-lock.json"
      - "packages/cross-csl-*/yarn.lock"
      - "test-app-mobile/package.json"
      - "test-app-mobile/package-lock.json"
      - "test-app-mobile/yarn.lock"
      - ".github/dependabot.yml"
      - ".github/workflows/dependency-review.yml"

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294
