name: PR Authoring

on:
  pull_request:
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  assignAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: Assign pull request to author
        if: github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.user.login != 'dependabot[bot]'
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          gh api \
            --method POST \
            "repos/${GH_REPO}/issues/${PR_NUMBER}/assignees" \
            -f "assignees[]=${PR_AUTHOR}"
