name: PR Labeler
on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@cb723cb76de12ba3d35e2e53586d4b5e72e9a8c2 # v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
